= Contributing

== Building and compiling sql2cypher

JDK 17 and Maven is required. Please run to test and package the project:

[source,bash]
----
./mvnw clean verify
----

There's a `fast` profile that will skip all the tests and validations:

[source,bash]
----
./mvnw -Dfast clean package
----

=== Native image (GraalVM) support

There's somewhat support to run this application as native image, but jOOQ itself is not yet fully GraalVM compatible (see https://github.com/jOOQ/jOOQ/issues/8779[jOOQ 8779]).

You can try with GraalVM 22.3.r17 and native image installed via

[source,bash]
----
./mvnw -Dnative clean package
./target/sql2cypher
----

The necessary `reflection-config.json` has been created partially via the GraalVM agent run like this

[source,bash]
----
./mvnw -Dfast clean package
JAVA_OPTS=-agentlib:native-image-agent=config-output-dir=target/generated-native-image-config target/assembly/bin/sql2cypher
----

And a printing breakpoint in the constructor of `org.jooq.impl.ArrayDataType.ArrayDataType` with the following content:

[source,java]
----
"{\"name\": \"" + elementType.getType().getName() + "[]\", \"allPublicConstructors\": true},"
----

== Tasks

=== Formatting sources / adding headers

When you add new files, you can run

[source,bash]
----
./mvnw license:format
----

to add required headers automatically.

=== Sorting the build file

To keep the dependencies in a predictable order, we enforce sorting of the build file. You can trigger this manually via

[source,bash]
----
./mvnw  sortpom:verify@sort
----
