= Sql2Cypher Experimental Transpiler from SQL to Cypher

This library is an experiment for converting SQL statements (first only read statements) to the appropriate Cypher equivalent.

It is currently in a pre-alpha stage.

== Example

For example:

[source,SQL]
----
SELECT t.a, t.b
FROM my_table AS t
WHERE t.a = 1
----

[source,Cypher]
----
MATCH (T:`MY_TABLE`) 
WHERE T.A = 1 
RETURN T.A, T.B
----

More concrete examples can be found in the link:src/test/resources[TCK].

* link:src/test/resources/simple.adoc[Simple Patterns]
* link:src/test/resources/expressions.adoc[Expressions]
* link:src/test/resources/predicates.adoc[Predicates]

== Usage

----
Usage: sql2cypher [-hV] [--disable-pretty-printing]
                  [--parse-name-case=<parseNameCase>]
                  [--sql-dialect=<sqlDialect>]
                  [--table-to-label-mapping=<String=String>]... <sql> [COMMAND]
Translates SQL statements to Cypher queries.
      <sql>       Any valid SQL statement that should be translated to Cypher
      --parse-name-case=<parseNameCase>
                  How to parse names; valid values are: AS_IS, LOWER,
                    LOWER_IF_UNQUOTED, UPPER, UPPER_IF_UNQUOTED, DEFAULT and
                    the default is LOWER_IF_UNQUOTED
      --table-to-label-mapping=<String=String>
                  A table name that should be mapped to a specific label,
                    repeat for multiple mappings
      --sql-dialect=<sqlDialect>
                  The SQL dialect to use for parsing; valid values are:
                    DEFAULT, CUBRID, DERBY, FIREBIRD, H2, HSQLDB, IGNITE,
                    MARIADB, MYSQL, POSTGRES, SQLITE, YUGABYTEDB and the
                    default is DEFAULT
      --disable-pretty-printing
                  Disables pretty printing
  -h, --help      Show this help message and exit.
  -V, --version   Print version information and exit.
Commands:
  help  Display help information about the specified command.
----

== Build & Usage

.Build
[source,shell]
----
./mvnw verify
./mvnw package
----

.Execute
[source,shell]
----
./target/assembly/bin/sql2cypher 'SELECT p.name, cast(p.age as STRING)
FROM "Person" AS p
WHERE p.age = 18 + rand()'
----

.Output
[source,cypher]
----
MATCH (p:Person)
WHERE p.age = (18 + rand())
RETURN p.name, toString(p.age)
----

=== Native Image

Sql2Cypher comes with native image support, so can build a binary that starts immediately and can be used in mass-translation from the command line.

It needs a Java 17+ version of graalvm installed, e.g. via SDKman: `sdk install java 22.3.r17-grl`

.Building native image
[source,shell]
----
gu install native-image
# Downloading: Component catalog from www.graalvm.org
# Processing Component: Native Image
# Component Native Image (org.graalvm.native-image) is already installed.

./mvnw -Pnative package
# ...  Finished generating 'sql2cypher' in 49,7s.

file  target/sql2cypher
# target/sql2cypher: Mach-O 64-bit executable arm64
----

.Testing native image
[source,shell]
----
time ./target/sql2cypher 'SELECT p.name, cast(p.age as STRING)
FROM "Person" AS p
WHERE p.age = 18 + rand()' 2>/dev/null
----

.Output and Runtime native image
[source]
----
MATCH (p:Person)
WHERE p.age = (18 + rand())
RETURN p.name, toString(p.age)

# 0,01s user 0,01s system 73% cpu 0,025 total
----

== Dependencies

* https://github.com/jOOQ[jOOQ - SQL DSL]
* https://github.com/neo4j-contrib/cypher-dsl[Neo4j Cypher-DSL]
* https://github.com/remkop/picocli[PicoCli]